---
title: "My Thesis Manuscript Timeline"
subtitle: "Journey of my thesis manuscript"
author: "Soundarya S"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: default
  tufte::tufte_handout:
    citation_package: natbib
    latex_engine: xelatex
  tufte::tufte_book:
    citation_package: natbib
    latex_engine: xelatex
---

```{r setup, include=FALSE}
library(tufte)
# invalidate cache when the tufte version changes
knitr::opts_chunk$set(tidy = FALSE, cache.extra = packageVersion("tufte"))
options(htmltools.dir.version = FALSE)
```


```{r myfaithfulsoldiers,message=FALSE,warning=FALSE}
library(readr)
library(tidyverse)
library(scales)
library(lubridate)
```

```{r loaddata,message=FALSE,warning=FALSE}
df <- read_csv("../data/thesismanuscript_milestones.csv")
head(df)
names(df)
```

```{r datacleaning,message=FALSE,warning=FALSE}
class(df$month)
class(df$year)
df$year <- as.integer(df$year)
df$date <- with(df, ymd(sprintf("%04d%02s%02s", year, month, 1)))
df <- df[with(df, order(date)), ]
head(df)
df <- df %>% select(-status)
df
```


```{r addfewdetails,message=FALSE,warning=FALSE}
positions <- c(
  0.5, -0.5, 1.0, -1.0, 1.25, -1.25, 1.5, -1.5,
  0.5, -0.5, 1.0, -1.0
)
directions <- c(1, -1)

line_pos <- data.frame(
  "date" = unique(df$date),
  "position" = rep(positions, length.out = length(unique(df$date))),
  "direction" = rep(directions, length.out = length(unique(df$date)))
)
```


```{r maindf,message=FALSE,warning=FALSE}
sound <- merge(x = df, y = line_pos, by = "date", all = TRUE)
head(sound)
```

```{r trickybusiness,message=FALSE,warning=FALSE}
month_buffer <- 1
month_date_range <- seq(min(sound$date) - months(month_buffer), max(sound$date) + months(month_buffer), by = "month")
month_format <- format(month_date_range, "%b")
month_df <- data.frame(month_date_range, month_format)
year_date_range <- seq(min(sound$date) - months(month_buffer), max(sound$date) + months(month_buffer), by = "year")
year_date_range <- as.Date(
  intersect(
    ceiling_date(year_date_range, unit = "year"),
    floor_date(year_date_range, unit = "year")
  ),
  origin = "1970-01-01"
)
year_format <- format(year_date_range, "%Y")
year_df <- data.frame(year_date_range, year_format)
```



```{r firstplot,message=FALSE,warning=FALSE}
timeline_plot <- ggplot(sound, aes(x = date, y = position, col = milestone, label = milestone))
timeline_plot
```

```{r addaesthetics,message=FALSE,warning=FALSE}
timeline_plot <- timeline_plot + labs(col = "Milestones")
Event_type_colors <- c("#C00000", "#FFC000", "#00B050", "#0070C0", "#C00000", "#FFC000", "#00B050", "#0070C0")
timeline_plot <- timeline_plot + scale_color_manual(values = Event_type_colors, drop = FALSE)
timeline_plot <- timeline_plot + theme_classic()
timeline_plot <- timeline_plot + geom_hline(
  yintercept = 0,
  color = "black", size = 0.3
)

timeline_plot <- timeline_plot + geom_segment(data = sound, aes(y = sound$position, yend = 0, xend = sound$date), color = "black", size = 0.2)

timeline_plot <- timeline_plot + geom_point(aes(y = position), size = 3)

timeline_plot <- timeline_plot + theme(
  axis.line.y = element_blank(),
  axis.text.y = element_blank(),
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  axis.ticks.y = element_blank(),
  axis.text.x = element_blank(),
  axis.ticks.x = element_blank(),
  axis.line.x = element_blank(),
  legend.position = "bottom"
)
```


```{r what,message=FALSE,warning=FALSE}
timeline_plot
```

```{r cleanup,message=FALSE,warning=FALSE}
timeline_plot <- timeline_plot + geom_text(data = month_df, aes(x = month_date_range, y = -0.15, label = month_format), size = 3.5, vjust = 0.5, color = "black", angle = 90)

timeline_plot <- timeline_plot + geom_text(data = year_df, aes(x = year_date_range, y = -0.35, label = year_format, fontface = "bold"), size = 3.5, color = "black")
text_offset <- 0.2
absolute_value <- (abs(sound$position))
text_position <- absolute_value + text_offset
sound$text_position <- text_position * sound$direction
timeline_plot <- timeline_plot + geom_text(aes(
  y = sound$text_position,
  label = sound$milestone
), size = 3.5, vjust = 0.6)
```


```{r final plot,message=FALSE,warning=FALSE, fig.height=6,fig.align="center",fig.width=8}
timeline_plot +
  labs(
    caption = "Visualization by Soundarya",
    title = "Soundarya's Thesis Manuscript Timeline"
  ) +
  theme(
    legend.position = "none",
    plot.title = element_text(size = 18, face = "bold", hjust = 0.5, color = "black"),
    plot.caption = element_text(color = "blue", face = "italic", size = 10),
  )
```
